AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# Description:
# Parameters:

Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 10

Resources:

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler.zip
      Handler: lambda.handler
